//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj2018_2019.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://schemas.datacontract.org/2004/07/ProjetBaye_Sakila.Model")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Address_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Manager_Staff_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Store_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Address_ID {
            get {
                return this.Address_IDField;
            }
            set {
                if ((this.Address_IDField.Equals(value) != true)) {
                    this.Address_IDField = value;
                    this.RaisePropertyChanged("Address_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Manager_Staff_ID {
            get {
                return this.Manager_Staff_IDField;
            }
            set {
                if ((this.Manager_Staff_IDField.Equals(value) != true)) {
                    this.Manager_Staff_IDField = value;
                    this.RaisePropertyChanged("Manager_Staff_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Store_ID {
            get {
                return this.Store_IDField;
            }
            set {
                if ((this.Store_IDField.Equals(value) != true)) {
                    this.Store_IDField = value;
                    this.RaisePropertyChanged("Store_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/ProjetBaye_Sakila.Model")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private proj2018_2019.ServiceReference1.City[] CitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Country_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Country_LibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] LAST_UPDATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public proj2018_2019.ServiceReference1.City[] Cities {
            get {
                return this.CitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CitiesField, value) != true)) {
                    this.CitiesField = value;
                    this.RaisePropertyChanged("Cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Country_ID {
            get {
                return this.Country_IDField;
            }
            set {
                if ((this.Country_IDField.Equals(value) != true)) {
                    this.Country_IDField = value;
                    this.RaisePropertyChanged("Country_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country_Lib {
            get {
                return this.Country_LibField;
            }
            set {
                if ((object.ReferenceEquals(this.Country_LibField, value) != true)) {
                    this.Country_LibField = value;
                    this.RaisePropertyChanged("Country_Lib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] LAST_UPDATE {
            get {
                return this.LAST_UPDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.LAST_UPDATEField, value) != true)) {
                    this.LAST_UPDATEField = value;
                    this.RaisePropertyChanged("LAST_UPDATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/ProjetBaye_Sakila.Model")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int City_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string City_LibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private proj2018_2019.ServiceReference1.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Country_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int City_ID {
            get {
                return this.City_IDField;
            }
            set {
                if ((this.City_IDField.Equals(value) != true)) {
                    this.City_IDField = value;
                    this.RaisePropertyChanged("City_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City_Lib {
            get {
                return this.City_LibField;
            }
            set {
                if ((object.ReferenceEquals(this.City_LibField, value) != true)) {
                    this.City_LibField = value;
                    this.RaisePropertyChanged("City_Lib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public proj2018_2019.ServiceReference1.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Country_ID {
            get {
                return this.Country_IDField;
            }
            set {
                if ((this.Country_IDField.Equals(value) != true)) {
                    this.Country_IDField = value;
                    this.RaisePropertyChanged("Country_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/ProjetBaye_Sakila.Model")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Address_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Staff_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Store_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Address_ID {
            get {
                return this.Address_IDField;
            }
            set {
                if ((this.Address_IDField.Equals(value) != true)) {
                    this.Address_IDField = value;
                    this.RaisePropertyChanged("Address_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Staff_ID {
            get {
                return this.Staff_IDField;
            }
            set {
                if ((this.Staff_IDField.Equals(value) != true)) {
                    this.Staff_IDField = value;
                    this.RaisePropertyChanged("Staff_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Store_ID {
            get {
                return this.Store_IDField;
            }
            set {
                if ((this.Store_IDField.Equals(value) != true)) {
                    this.Store_IDField = value;
                    this.RaisePropertyChanged("Store_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/ProjetBaye_Sakila.Model")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Address_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address_LibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address_Lib2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> City_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Postal_CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Address_ID {
            get {
                return this.Address_IDField;
            }
            set {
                if ((this.Address_IDField.Equals(value) != true)) {
                    this.Address_IDField = value;
                    this.RaisePropertyChanged("Address_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address_Lib {
            get {
                return this.Address_LibField;
            }
            set {
                if ((object.ReferenceEquals(this.Address_LibField, value) != true)) {
                    this.Address_LibField = value;
                    this.RaisePropertyChanged("Address_Lib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address_Lib2 {
            get {
                return this.Address_Lib2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address_Lib2Field, value) != true)) {
                    this.Address_Lib2Field = value;
                    this.RaisePropertyChanged("Address_Lib2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> City_ID {
            get {
                return this.City_IDField;
            }
            set {
                if ((this.City_IDField.Equals(value) != true)) {
                    this.City_IDField = value;
                    this.RaisePropertyChanged("City_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postal_Code {
            get {
                return this.Postal_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Postal_CodeField, value) != true)) {
                    this.Postal_CodeField = value;
                    this.RaisePropertyChanged("Postal_Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film", Namespace="http://schemas.datacontract.org/2004/07/PROJETBAYE2018.Modeltest")]
    [System.SerializableAttribute()]
    public partial class Film : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Film_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LenghtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Original_Language_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Release_yearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Rental_durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Rental_rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Replacement_costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Special_featuresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Film_ID {
            get {
                return this.Film_IDField;
            }
            set {
                if ((this.Film_IDField.Equals(value) != true)) {
                    this.Film_IDField = value;
                    this.RaisePropertyChanged("Film_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageID {
            get {
                return this.LanguageIDField;
            }
            set {
                if ((this.LanguageIDField.Equals(value) != true)) {
                    this.LanguageIDField = value;
                    this.RaisePropertyChanged("LanguageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Lenght {
            get {
                return this.LenghtField;
            }
            set {
                if ((this.LenghtField.Equals(value) != true)) {
                    this.LenghtField = value;
                    this.RaisePropertyChanged("Lenght");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Original_Language_ID {
            get {
                return this.Original_Language_IDField;
            }
            set {
                if ((this.Original_Language_IDField.Equals(value) != true)) {
                    this.Original_Language_IDField = value;
                    this.RaisePropertyChanged("Original_Language_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Release_year {
            get {
                return this.Release_yearField;
            }
            set {
                if ((object.ReferenceEquals(this.Release_yearField, value) != true)) {
                    this.Release_yearField = value;
                    this.RaisePropertyChanged("Release_year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rental_duration {
            get {
                return this.Rental_durationField;
            }
            set {
                if ((this.Rental_durationField.Equals(value) != true)) {
                    this.Rental_durationField = value;
                    this.RaisePropertyChanged("Rental_duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rental_rate {
            get {
                return this.Rental_rateField;
            }
            set {
                if ((this.Rental_rateField.Equals(value) != true)) {
                    this.Rental_rateField = value;
                    this.RaisePropertyChanged("Rental_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Replacement_cost {
            get {
                return this.Replacement_costField;
            }
            set {
                if ((this.Replacement_costField.Equals(value) != true)) {
                    this.Replacement_costField = value;
                    this.RaisePropertyChanged("Replacement_cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Special_features {
            get {
                return this.Special_featuresField;
            }
            set {
                if ((object.ReferenceEquals(this.Special_featuresField, value) != true)) {
                    this.Special_featuresField = value;
                    this.RaisePropertyChanged("Special_features");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Ifundamentals")]
    public interface Ifundamentals {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/Ajouter", ReplyAction="http://tempuri.org/Ifundamentals/AjouterResponse")]
        void Ajouter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/Ajouter", ReplyAction="http://tempuri.org/Ifundamentals/AjouterResponse")]
        System.Threading.Tasks.Task AjouterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetStores", ReplyAction="http://tempuri.org/Ifundamentals/GetStoresResponse")]
        proj2018_2019.ServiceReference1.Store[] GetStores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetStores", ReplyAction="http://tempuri.org/Ifundamentals/GetStoresResponse")]
        System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Store[]> GetStoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetCountries", ReplyAction="http://tempuri.org/Ifundamentals/GetCountriesResponse")]
        proj2018_2019.ServiceReference1.Country[] GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetCountries", ReplyAction="http://tempuri.org/Ifundamentals/GetCountriesResponse")]
        System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Country[]> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetStaffs", ReplyAction="http://tempuri.org/Ifundamentals/GetStaffsResponse")]
        proj2018_2019.ServiceReference1.Staff[] GetStaffs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetStaffs", ReplyAction="http://tempuri.org/Ifundamentals/GetStaffsResponse")]
        System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Staff[]> GetStaffsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetCities", ReplyAction="http://tempuri.org/Ifundamentals/GetCitiesResponse")]
        proj2018_2019.ServiceReference1.City[] GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetCities", ReplyAction="http://tempuri.org/Ifundamentals/GetCitiesResponse")]
        System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.City[]> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetAddresses", ReplyAction="http://tempuri.org/Ifundamentals/GetAddressesResponse")]
        proj2018_2019.ServiceReference1.Address[] GetAddresses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetAddresses", ReplyAction="http://tempuri.org/Ifundamentals/GetAddressesResponse")]
        System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Address[]> GetAddressesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddStores", ReplyAction="http://tempuri.org/Ifundamentals/AddStoresResponse")]
        void AddStores(proj2018_2019.ServiceReference1.Store store);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddStores", ReplyAction="http://tempuri.org/Ifundamentals/AddStoresResponse")]
        System.Threading.Tasks.Task AddStoresAsync(proj2018_2019.ServiceReference1.Store store);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddStaff", ReplyAction="http://tempuri.org/Ifundamentals/AddStaffResponse")]
        void AddStaff(proj2018_2019.ServiceReference1.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddStaff", ReplyAction="http://tempuri.org/Ifundamentals/AddStaffResponse")]
        System.Threading.Tasks.Task AddStaffAsync(proj2018_2019.ServiceReference1.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddStaff2", ReplyAction="http://tempuri.org/Ifundamentals/AddStaff2Response")]
        string AddStaff2(proj2018_2019.ServiceReference1.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddStaff2", ReplyAction="http://tempuri.org/Ifundamentals/AddStaff2Response")]
        System.Threading.Tasks.Task<string> AddStaff2Async(proj2018_2019.ServiceReference1.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddAddress", ReplyAction="http://tempuri.org/Ifundamentals/AddAddressResponse")]
        void AddAddress(proj2018_2019.ServiceReference1.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/AddAddress", ReplyAction="http://tempuri.org/Ifundamentals/AddAddressResponse")]
        System.Threading.Tasks.Task AddAddressAsync(proj2018_2019.ServiceReference1.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/UpdateStaff", ReplyAction="http://tempuri.org/Ifundamentals/UpdateStaffResponse")]
        void UpdateStaff(int idStaff, int IdStore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/UpdateStaff", ReplyAction="http://tempuri.org/Ifundamentals/UpdateStaffResponse")]
        System.Threading.Tasks.Task UpdateStaffAsync(int idStaff, int IdStore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/LastId", ReplyAction="http://tempuri.org/Ifundamentals/LastIdResponse")]
        int LastId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/LastId", ReplyAction="http://tempuri.org/Ifundamentals/LastIdResponse")]
        System.Threading.Tasks.Task<int> LastIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetFilms", ReplyAction="http://tempuri.org/Ifundamentals/GetFilmsResponse")]
        proj2018_2019.ServiceReference1.Film[] GetFilms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ifundamentals/GetFilms", ReplyAction="http://tempuri.org/Ifundamentals/GetFilmsResponse")]
        System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Film[]> GetFilmsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IfundamentalsChannel : proj2018_2019.ServiceReference1.Ifundamentals, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IfundamentalsClient : System.ServiceModel.ClientBase<proj2018_2019.ServiceReference1.Ifundamentals>, proj2018_2019.ServiceReference1.Ifundamentals {
        
        public IfundamentalsClient() {
        }
        
        public IfundamentalsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IfundamentalsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfundamentalsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IfundamentalsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ajouter() {
            base.Channel.Ajouter();
        }
        
        public System.Threading.Tasks.Task AjouterAsync() {
            return base.Channel.AjouterAsync();
        }
        
        public proj2018_2019.ServiceReference1.Store[] GetStores() {
            return base.Channel.GetStores();
        }
        
        public System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Store[]> GetStoresAsync() {
            return base.Channel.GetStoresAsync();
        }
        
        public proj2018_2019.ServiceReference1.Country[] GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Country[]> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public proj2018_2019.ServiceReference1.Staff[] GetStaffs() {
            return base.Channel.GetStaffs();
        }
        
        public System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Staff[]> GetStaffsAsync() {
            return base.Channel.GetStaffsAsync();
        }
        
        public proj2018_2019.ServiceReference1.City[] GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.City[]> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
        
        public proj2018_2019.ServiceReference1.Address[] GetAddresses() {
            return base.Channel.GetAddresses();
        }
        
        public System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Address[]> GetAddressesAsync() {
            return base.Channel.GetAddressesAsync();
        }
        
        public void AddStores(proj2018_2019.ServiceReference1.Store store) {
            base.Channel.AddStores(store);
        }
        
        public System.Threading.Tasks.Task AddStoresAsync(proj2018_2019.ServiceReference1.Store store) {
            return base.Channel.AddStoresAsync(store);
        }
        
        public void AddStaff(proj2018_2019.ServiceReference1.Staff staff) {
            base.Channel.AddStaff(staff);
        }
        
        public System.Threading.Tasks.Task AddStaffAsync(proj2018_2019.ServiceReference1.Staff staff) {
            return base.Channel.AddStaffAsync(staff);
        }
        
        public string AddStaff2(proj2018_2019.ServiceReference1.Staff staff) {
            return base.Channel.AddStaff2(staff);
        }
        
        public System.Threading.Tasks.Task<string> AddStaff2Async(proj2018_2019.ServiceReference1.Staff staff) {
            return base.Channel.AddStaff2Async(staff);
        }
        
        public void AddAddress(proj2018_2019.ServiceReference1.Address address) {
            base.Channel.AddAddress(address);
        }
        
        public System.Threading.Tasks.Task AddAddressAsync(proj2018_2019.ServiceReference1.Address address) {
            return base.Channel.AddAddressAsync(address);
        }
        
        public void UpdateStaff(int idStaff, int IdStore) {
            base.Channel.UpdateStaff(idStaff, IdStore);
        }
        
        public System.Threading.Tasks.Task UpdateStaffAsync(int idStaff, int IdStore) {
            return base.Channel.UpdateStaffAsync(idStaff, IdStore);
        }
        
        public int LastId() {
            return base.Channel.LastId();
        }
        
        public System.Threading.Tasks.Task<int> LastIdAsync() {
            return base.Channel.LastIdAsync();
        }
        
        public proj2018_2019.ServiceReference1.Film[] GetFilms() {
            return base.Channel.GetFilms();
        }
        
        public System.Threading.Tasks.Task<proj2018_2019.ServiceReference1.Film[]> GetFilmsAsync() {
            return base.Channel.GetFilmsAsync();
        }
    }
}
